# -*- coding: utf-8 -*-
"""HW 1.1.ipy

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nupEZYwMdop-soxBSfftj91nfPu7saCS
"""

# Задача 1.1.

# Есть строка с перечислением песен

my_favorite_songs = 'Waste a Moment, Staying\' Alive, A Sorta Fairytale, Start Me Up, New Salvation'
# Выведите на консоль с помощью индексации строки, последовательно: первый трек, последний, второй, второй с конца
# Нельзя переопределять my_favorite_songs и запятая не должна выводиться.
# Решение
greeting = 'Waste a Moment, Staying\' Alive, A Sorta Fairytale, Start Me Up, New Salvation'
# Считаем индексы элементов
len('Waste a Moment, Staying\' Alive, A Sorta Fairytale, Start Me Up, New Salvation')
# W a s t e   a   M o m  e  n  t  ,      S  t  a  y  i  n  g  \   '   A  l  i v  e   ,     A    S  o  r  t  a     F  a  i  r  y  t  a  l   e  ,    S  t  a   r t      M  e    U  p  ,      N e w       S  a   l v  a   t i o n
# 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15  16 17 18 19 20 21 22  23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67  68 69 70 71 72 73 74 75 76
greeting [ 0:14] + greeting [63:77] +greeting[15:30]+ greeting[51:62]