# -*- coding: utf-8 -*-
"""complete_task_2.1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UCOqZL0RtKxIL3vRT9uA1oP-q1-fl6hg

# Задача 2.1.

# Создайте две функции maximum и minimum,
# которые получают список целых чисел в качестве входных данных
# и возвращают наибольшее и наименьшее число в этом списке соответственно.
# Например,
# * [4,6,2,1,9,63,-134,566]         -> max = 566, min = -134
# * [-52, 56, 30, 29, -54, 0, -110] -> min = -110, max = 56
# * [42, 54, 65, 87, 0]             -> min = 0, max = 87
# * [5]                             -> min = 5, max = 5
## функции sorted, max и min использовать нельзя!
"""

data = [12, 4, 54, 29, 46, 36, 72, 99, 85]
def minimum(data):
  n = len(data)
  for i in range(n -1):
    for j in range(n - i - 1):
      if data[j] > data[j+1]:
        data[j],data[j+1] = data[j+1],data[j]
  return data
minimum(data)
print(data[0])





data = [12, 4, 54, 29, 46, 36, 72, 99, 85]
def maximum(data):
  n = len(data)
  for i in range(n -1):
    for j in range(n - i - 1):
      if data[j] < data[j+1]:
        data[j],data[j+1] = data[j+1],data[j]
  return data
maximum(data)
print(data[0])