# -*- coding: utf-8 -*-
"""complete_task_4_1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eiH9G9kTGZWyi5thY5a5wEvppMC-8OZ8
"""

import sqlite3

def get_connection():
  connection = sqlite3.connect("teachers.db")
  return connection

def close_connection(connection):
  if connection:
    connection.close()

def join_method(school_id):
  try:
    connection = get_connection()
    cursor = connection.cursor()
    sql_query = "SELECT * FROM Students JOIN School ON Students.School_Id = School.School_Id WHERE Students.School_Id = ?"
    cursor.execute(sql_query,(school_id,))
    records = cursor.fetchall()
    close_connection(connection)
    print ("Данные по студентам")
    for row in records:
      print ("ID студента:", row[0])
      print ("Имя студента:", row[1])
      print ("ID школы:", row[2])
      print ("Название школы:", row[4])
  except (Exception, sqlite3.Error) as error:
    print ("Ошибка в получении данных: ", error)

join_method(2)